// Conteúdo das 12 peças (feed 4:5, 1080x1350) da Opus SoftWorks.
// Título: <em> = Instrument Serif itálico; <mark> = destaque coral.
// scene = objeto 3D de src/scenes.js; note = bilhete de papel; bursts = adesivos coral.

export const posts = [
  { n:1, date:'2026-10-12', dow:'Seg', theme:'dark', pilar:'Tráfego pago', scene:'chess',
    lead:'Antes de aumentar a verba,', title:'você paga por clique ou por <mark>cliente?</mark>',
    note:{ t:'Campanha boa se mede em <b>venda</b>, não em clique.', x:690, y:1000, r:-4 }, bursts:[{x:150,y:620,s:120,r:10}],
    body:'Meta e Google guiados por custo por cliente e retorno.',
    legenda:'Clique barato não paga boleto. Cliente, sim.\n\nNa Opus SoftWorks, as campanhas em Meta e Google são guiadas por custo por cliente, taxa de fechamento e retorno sobre o investimento — não por curtida nem clique.\n\nQuer saber o que a sua campanha entrega de verdade? Fala com um especialista pelo link da bio.',
    hashtags:'#trafegopago #metaads #googleads #marketingdigital #goiania #opussoftworks' },
  { n:2, date:'2026-10-14', dow:'Qua', theme:'light', pilar:'Sites', scene:'phoneSite',
    lead:'Não adianta ter visita', title:'se o seu site não <em>sabe</em> <mark>vender.</mark>',
    note:{ t:'Visitante sem próximo passo vira <b>aba fechada.</b>', x:90, y:1010, r:3 }, bursts:[{x:880,y:600,s:110,r:-8}],
    body:'Sites rápidos e claros, pensados para vender.',
    legenda:'Site bonito que não leva ninguém ao WhatsApp é cartão de visita caro.\n\nA Opus SoftWorks faz sites rápidos e claros, com caminho direto até o contato — pensados pra converter visita em cliente.\n\nSeu site hoje deixa óbvio qual é o próximo passo?',
    hashtags:'#siteprofissional #webdesign #conversao #goiania #opussoftworks' },
  { n:3, date:'2026-10-16', dow:'Sex', theme:'dark', pilar:'Sistemas', scene:'puzzle',
    lead:'Planilha não é sistema.', title:'Sua operação precisa <mark>encaixar.</mark>',
    note:{ t:'Informação centralizada, <b>zero retrabalho.</b>', x:640, y:1030, r:-3 }, bursts:[{x:160,y:1010,s:100,r:0}],
    body:'Mapeamos a operação e eliminamos tarefa repetitiva.',
    legenda:'Quando cada informação mora num lugar, a operação trava.\n\nCom sistemas e automações, a Opus SoftWorks mapeia o seu processo, elimina tarefas repetitivas e centraliza tudo num lugar só.\n\nQuantas planilhas você abre pra fechar uma venda? Conta aqui.',
    hashtags:'#sistemadegestao #automacao #processos #gestaoempresarial #opussoftworks' },
  { n:4, date:'2026-10-19', dow:'Seg', theme:'light', pilar:'Autoridade', scene:'dice',
    lead:'O que move a Opus SoftWorks', title:'Resultado não é <em>sorte.</em><br><mark>É entrega.</mark>',
    note:null, bursts:[{x:860,y:560,s:120,r:12},{x:120,y:1120,s:70,r:0}],
    body:'Estratégia, tecnologia e IA para empresas que querem crescer com clareza.',
    legenda:'Resultado não é sorte. É entrega.\n\nA Opus SoftWorks une tráfego pago, sistemas de gestão e sites sob uma mesma estratégia, pra empresas que já faturam e querem crescer com processo.\n\nSalva esse post pra lembrar na hora de escolher um parceiro.',
    hashtags:'#opussoftworks #marketingdigital #trafegopago #sistemas #sites #goiania' },
  { n:5, date:'2026-10-21', dow:'Qua', theme:'dark', pilar:'Tráfego pago', scene:'coins',
    lead:'Lead barato que não compra', title:'CPL baixo não paga <em>a</em> <mark>conta.</mark>',
    note:{ t:'Custo por cliente, taxa de fechamento e <b>retorno.</b>', x:90, y:1010, r:4 }, bursts:[{x:900,y:640,s:100,r:-10}],
    body:'O número que importa é quanto volta por real investido.',
    legenda:'Lead barato que não fecha só enche o CRM.\n\nPor isso a gente acompanha custo por cliente, taxa de fechamento e retorno sobre o investimento — e explica tudo em linguagem simples, nas reuniões periódicas.\n\nQual métrica você acompanha hoje?',
    hashtags:'#roas #cpl #trafegopago #performance #opussoftworks' },
  { n:6, date:'2026-10-23', dow:'Sex', theme:'light', pilar:'Método', scene:'steps',
    lead:'Como trabalhamos', title:'4 etapas. <em>Zero</em> <mark>improviso.</mark>',
    note:{ t:'Diagnóstico · Estratégia ·<br>Implementação · <b>Otimização</b>', x:640, y:1040, r:-3 }, bursts:[{x:150,y:620,s:90,r:0}],
    body:'Você sempre sabe em que etapa o seu projeto está.',
    legenda:'O método da Opus SoftWorks:\n\n01 Diagnóstico: operação, metas, números e gargalos.\n02 Estratégia: prioridades, onde investir e o que medir.\n03 Implementação: campanhas, sistemas e sites funcionando juntos.\n04 Otimização contínua: analisar, ajustar e repetir.\n\nO primeiro passo é o diagnóstico gratuito. Link na bio.',
    hashtags:'#metodo #processo #estrategia #opussoftworks' },
  { n:7, date:'2026-10-26', dow:'Seg', theme:'dark', pilar:'Sites', scene:'stopwatch',
    lead:'Rápido e claro', title:'Seu site tem <em>poucos</em> <mark>segundos</mark> pra convencer.',
    note:{ t:'Primeira tela: o que você faz, pra quem e <b>o próximo passo.</b>', x:640, y:1030, r:-4 }, bursts:[{x:150,y:700,s:100,r:15}],
    body:'Carregamento rápido e mensagem direta seguram o visitante.',
    legenda:'O visitante decide rápido se fica ou sai.\n\nPor isso a primeira tela precisa dizer o que você faz, pra quem e qual é o próximo passo — e carregar rápido, principalmente no celular.\n\nQuer uma opinião sincera sobre o seu site? Chama a gente.',
    hashtags:'#site #ux #landingpage #conversao #opussoftworks' },
  { n:8, date:'2026-10-28', dow:'Qua', theme:'light', pilar:'Sistemas', scene:'chat',
    lead:'Lead que espera, esfria.', title:'Quem responde primeiro, <mark>fecha.</mark>',
    note:{ t:'Automação pra nenhum contato ficar <b>sem retorno.</b>', x:80, y:1020, r:3 }, bursts:[{x:900,y:620,s:100,r:0}],
    body:'Atendimento organizado também é estratégia de venda.',
    legenda:'Todo lead que fica sem resposta vira cliente de alguém.\n\nCom automações e um processo comercial organizado, cada contato recebe retorno no tempo certo — sem depender da memória de ninguém.\n\nQuantos leads estão esperando resposta no seu WhatsApp agora?',
    hashtags:'#vendas #crm #automacao #whatsapp #opussoftworks' },
  { n:9, date:'2026-10-30', dow:'Sex', theme:'dark', pilar:'Autoridade', scene:'calendar',
    lead:'Entrega com processo', title:'Prazo cumprido é <em>o</em> <mark>mínimo.</mark>',
    note:{ t:'Reuniões periódicas e relatórios em <b>linguagem simples.</b>', x:90, y:1030, r:4 }, bursts:[],
    body:'Você acompanha cada etapa, sem surpresa no fim do mês.',
    legenda:'Cumprir prazo não é diferencial, é obrigação.\n\nNa Opus SoftWorks você acompanha tudo em reuniões periódicas, com relatórios em linguagem simples — sem jargão e sem surpresa.\n\nO que você mais valoriza num parceiro? Deixa aqui.',
    hashtags:'#entrega #processo #transparencia #opussoftworks' },
  { n:10, date:'2026-11-02', dow:'Seg', theme:'light', pilar:'Autoridade', scene:'gears',
    lead:'Tráfego, sistema e site', title:'Três fornecedores. <em>Zero</em> <mark>conversa.</mark>',
    note:{ t:'Na Opus, é <b>uma estratégia só.</b>', x:660, y:1060, r:-4 }, bursts:[{x:140,y:640,s:90,r:0}],
    body:'Três frentes trabalhando pro mesmo número: o seu resultado.',
    legenda:'Agência de tráfego, desenvolvedor de site e fornecedor de sistema raramente conversam entre si.\n\nNa Opus SoftWorks as três frentes ficam sob a mesma estratégia, com as mesmas metas.\n\nMarca alguém que ainda coordena três fornecedores.',
    hashtags:'#marketing #estrategia #integracao #opussoftworks' },
  { n:11, date:'2026-11-04', dow:'Qua', theme:'dark', pilar:'Diagnóstico', scene:'diamond',
    lead:'Diagnóstico gratuito', title:'Quanto vale o lead que você <mark>perdeu?</mark>',
    note:{ t:'Mostramos onde a sua operação <b>vaza venda.</b>', x:90, y:1030, r:4 }, bursts:[{x:900,y:1000,s:90,r:10}],
    body:'Sem compromisso. Operação, metas, números e gargalos.',
    legenda:'Todo negócio perde lead em algum ponto: no anúncio, no site ou no atendimento.\n\nO diagnóstico gratuito da Opus SoftWorks olha sua operação, metas, números e gargalos e aponta o que fazer primeiro.\n\nSem compromisso. Link na bio.',
    hashtags:'#diagnostico #vendas #marketing #goiania #opussoftworks' },
  { n:12, date:'2026-11-06', dow:'Sex', theme:'light', pilar:'Conversão', scene:'infinity',
    lead:'Vender mais. Operar melhor.', title:'Crescer com <em>muito</em> <mark>mais clareza.</mark>',
    note:{ t:'WhatsApp<br><b>(62) 99410-6910</b>', x:690, y:1060, r:-4 }, bursts:[],
    body:'Estratégia, tecnologia e IA. Goiânia e todo o Brasil.',
    legenda:'Estratégia, tecnologia e IA para empresas que querem vender mais, operar melhor e crescer com clareza.\n\nFale com um especialista da Opus SoftWorks e peça seu diagnóstico gratuito: (62) 99410-6910, ou pelo link da bio.',
    hashtags:'#opussoftworks #diagnosticogratuito #trafegopago #sistemas #sites #goiania' },
];
